homeassistant:
#  # Name of the location where Home Assistant is running
#  name: Beach House
#  # Location required to calculate the time the sun rises and sets
#  latitude: !secret home_latitude
#  longitude: !secret home_longitude
#  # Impacts weather/sunrise data (altitude above sea level in meters)
#  elevation: 0
#  # metric for Metric, imperial for Imperial
#  unit_system: imperial
#  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#  time_zone: America/New_York
#  # Customization file
#  auth_providers:
#    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret http_password
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/tmp'
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/hass-bha-icons.html
  javascript_version: latest

http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_certificate_key_path
  base_url: !secret base_ha_url

duckdns:
  domain: !secret ha_domain_name
  access_token: !secret duckdns_access_token

spotify:
  client_id: 0fc021fc3f3f4efea3dbbc23a483bb39
  client_secret: 21947ba4f17c420eb68c18128f85adce

#logger:
#  default: critical
  
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    
withings:
  client_id: !secret withings_id
  client_secret: !secret withings_secret
  profiles:
    - paul
    - tracy
    
recorder:
  purge_interval: 1
  purge_keep_days: 8
  db_url: !secret maria_db_info

device_tracker:
  - platform: asuswrt
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
#      hide_if_away: false
  - platform: google_maps
    username: !secret notificationemail
    max_gps_accuracy: 150
  - platform: composite
    name: Paul_All
    entity_id:
      - device_tracker.life360_paul
#      - device_tracker.pauls_iphone
      - device_tracker.google_maps_118013912887885302155
  - platform: composite
    name: Tracy_All
    entity_id:
      - device_tracker.life360_tracy
#      - device_tracker.tracys_iphone
      - device_tracker.google_maps_116112519745623760034
     
asuswrt:
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_password
    protocol: ssh

emulated_hue:
  host_ip: 192.168.1.12
  expose_by_default: false

hue:
  bridges:
    - host: 192.168.1.52
      allow_unreachable: true
      allow_hue_groups: true

homekit:
  filter:
    include_entities:
      - input_boolean.paul_present
      - input_boolean.tracy_present
      - input_boolean.theater_room_tv_power
      - input_boolean.bedroom_tv_power
      - cover.garage_door_opener

mobile_app:

discovery:
  enable:
#    - homekit
  ignore:
#    - philips_hue
    - apple_tv
    #- plex_mediaserver
    - igd
    
google:
  client_id: !secret google_calendar_id
  client_secret: !secret google_calendar_secret

api:

remote:
  - platform: harmony
    host: 192.168.1.51
    name: Living Room Harmony Hub
  - platform: harmony
    host: 192.168.1.50
    name: Theater Room Harmony Hub 

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: 192.168.1.12
  username: !secret mqtt_username
  password: !secret mqtt_password
#ecobee:
#  api_key: !secret ecobee_api_key
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

media_player:
  - platform: braviatv_psk
    name: Living Room TV
    host: 192.168.1.80
    psk: 1234
    mac: 04:5D:4B:AA:70:89
    amp: True
    android: True
#  - platform: vizio
#    host: 192.168.1.82
#    access_token: Z6xoq7pviz
#    name: Theater Room TV Control
#  - platform: vizio
#    host: 192.168.1.84
#    access_token: Zbo7pxfs55
#    name: Bedroom TV Control
  - platform: braviatv
    host: 192.168.1.80

#alexa_media:
#  accounts:
#    email: !secret amazon_user
#    password: !secret amazon_password
#    url: amazon.com
#    exclude_devices:
#    - "This Device"
#    - "Paul's Alexa Apps"
#    - "Tracy's Alexa Apps"
#    - "Downstairs"
#    - "My Dash"
#    - "Living Room"
#    - "old_dot2"
#    - "old_dot"
#    - "office_show"
#    - "Amazon Tap"
#    - "portable"

input_number:
  commute_start_time:
    name: Commute Start Time
    min: 0
    max: 100000000000
  vehicles_in_driveway:
    name: Vehicles in Parking Pad
    min: 0
    max: 6
  people_in_yard:
    min: 0
    max: 10

shell_command:
  car_lock: python3.7 /home/homeassistant/.homeassistant/python_scripts/lock_car.py
  car_start: python3.7 /home/homeassistant/.homeassistant/python_scripts/start_car.py
  
# Zigbee
zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

# Zwave
zwave: !include zwave.yaml

circadian_lighting:

switch:
  - platform: circadian_lighting
    name: circadian_livingroom
    lights_rgb:
      - light.living_room_color_lights
  - platform: circadian_lighting
    name: circadian_downstairs
    lights_rgb:
      - light.all_downstairs_color_lights

#ffmpeg:
#  ffmpeg_bin: /usr/bin/avconv

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave

stream:

image_processing: !include image_processing.yaml

ios:
  push:
    categories:
      - name: Garage Alert
        identifier: 'garage_alert'
        actions:
          - identifier: 'CANCEL_GARAGE_ALERT'
            title: 'Cancel Alert'
          - identifier: 'CLOSE_GARAGE'
            title: 'Close Garage'
      - name: Shopping Alert
        identifier: 'shopping_alert'
        actions:
          - identifier: 'CANCEL_SHOPPING_ALERT'
            title: 'No'
          - identifier: 'OPEN_GARAGE_WHEN_I_GET_HOME'
            title: 'Yes'
      - name: Guest Alert
        identifier: 'guest_alert'
        actions:
          - identifier: 'GUESTS_GONE'
            title: 'No'
          - identifier: 'GUESTS_HOME'
            title: 'Yes'

timer:
  guests_just_arrived:
    duration: '00:07:00'
  paul_just_arrived:
    duration: '00:07:00'
  tracy_just_arrived:
    duration: '00:07:00'
  frog_tv_reset:
    duration: '00:05:00'
  camera_action:
    duration: '00:00:60'

logbook: !include logbook.yaml
alexa: !include alexa.yaml
notify: !include notify.yaml
#zone: !include zones.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
input_select: !include input_selects.yaml
input_text: !include input_texts.yaml
input_datetime: !include input_datetimes.yaml
input_boolean: !include input_booleans.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
alert: !include alerts.yaml
history: !include history.yaml
camera: !include cameras.yaml
scene: !include scenes.yaml
light: !include light.yaml