#- platform: group
#  name: All Downstairs Color Lights
#  entities:
#    - light.left_shelf_lights
#    - light.tv_backlights
#    - light.right_shelf_lights
#    - light.kitchen_cabinet_tops
#    - light.kitchen_cabinet_bottoms
#    - light.living_room_lamp_one
#    - light.living_room_lamp_two
#    - light.alcove_light
#- platform: group
#  name: Living Room Color Lights
#  entities:
#    - light.left_shelf_lights
#    - light.tv_backlights
#    - light.right_shelf_lights
#    - light.living_room_lamp_one
#    - light.living_room_lamp_two
#- platform: group
#  name: Kitchen Color Lights
#  entities:
#    - light.kitchen_cabinet_tops
#    - light.kitchen_cabinet_bottoms
#    - light.alcove_light
#- platform: group
#  name: Shelf Color Lights
#  entities:
#    - light.left_shelf_lights
#    - light.tv_backlights
#    - light.right_shelf_lights
#- platform: group
#  name: Shelf Only Color Lights
#  entities:
#    - light.left_shelf_lights
#    - light.right_shelf_lights
#- platform: group
#  name: Kitchen Cabinet Color Lights
#  entities:
#    - light.kitchen_cabinet_tops
#    - light.kitchen_cabinet_bottoms
- platform: group
  name: goodnight hue lights
  entities:
    - light.office_lamp_two
    - light.ashleys_room_lamp
    - light.guest_bedroom_lamp
- platform: group
  name: Kitchen Ceiling Lights
  entities:
    - light.kitchen_counter_light
    - light.kitchen_island_light
- platform: group
  name: Office Lamps
  entities:
    - light.office_lamp_two
    - light.office_lamp_one
- platform: template
  lights:
    alexa_virtual:
      friendly_name: "Alexa Dummy Light"
      turn_on:
      turn_off:
      set_level:
- platform: switch
  name: Sconce Light
  entity_id: switch.sconce_light
- platform: switch
  name: Stairwell Light
  entity_id: switch.stairwell_light
- platform: switch
  name: Christmas Tree
  entity_id: switch.living_room_plug_two
- platform: switch
  name: Office Lamp One
  entity_id: switch.office_lamp_one
