binary_sensor:
  - platform: template
    sensors:
      motion_sensor_attic_motion:
        value_template: "{{ is_state('sensor.motion_sensor_attic_burglar', '8') }}"
        friendly_name: "Motion Sensor (Attic)"
        device_class: motion
        entity_id:  sensor.motion_sensor_attic_burglar

      motion_sensor_attic_tamper:
        value_template: "{{ is_state('sensor.motion_sensor_attic_burglar', '3') }}"
        friendly_name: "Attic Multisensor Tamper"
        device_class: safety
        entity_id:  sensor.motion_sensor_attic_burglar
